apiVersion: apps/v1
kind: Deloyment
metadata: 
  name: fixit
spec:
  replicas: 2
  selector:
    matchLables:
      app: fixit
  template:
    metadata:
      lables:
        app: fixit
  spec:
    containers:
      - name: fixit
        image: fixit:v1
        ports:
          - port: 3000
            containerPort: 3000
